id: IDBC9B9BD
legacy_id: P010489
ocr_import_info:
  bdrc_scan_id: W30155
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T07:29:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:22:01.850449+00:00'
last_modified: 2022-09-03 19:22:22.007798
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30155
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30155
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་བཟང་ཐུབ་བསྟན་དབང་ཕྱུག་འཇིགས་མེད་རྒྱ་མཚོ་དགེ་ལེགས་རབ་རྒྱས་ཀྱི་རྣམ་ཐར་དད་པའི་པད་ཚལ་བཞད་པའི་ཉི་འོད།
  author: བསྟན་པའི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.5913367966429895
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I6477:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6477
      total_pages: 736
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6477.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5913367966429895
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
