id: P010489
initial_creation_type: ocr
source_metadata:
  id: bdr:W30155
  title: བློ་བཟང་ཐུབ་བསྟན་དབང་ཕྱུག་འཇིགས་མེད་རྒྱ་མཚོ་དགེ་ལེགས་རབ་རྒྱས་ཀྱི་རྣམ་ཐར་དད་པའི་པད་ཚལ་བཞད་པའི་ཉི་འོད།
  author: ''
  volumes:
    55da12e54fec48bb9e86450dc524a79e:
      image_group_id: I6477
      title: ''
      volume_number: 1
      total_pages: 736
